spring:
  application:
    name: flowable-demo
  liquibase:
    enabled: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect


  datasource:
    url: jdbc:postgresql://localhost:5432/flowable
    username: flowable
    password: flowable
    driver-class-name: org.postgresql.Driver




  security:
    user:
      name: admin
      password: admin
      roles: ADMIN,USER

flowable:
  rest-api-enabled: true
  # Основная конфигурация
  async-executor-activate: true
  database-schema-update: true
  history-level: none




server:
  port: ${server.port:8095}
  servlet:
    context-path: /



logging:
  level:
    com.mycompany.myapp.mapper: DEBUG
