  DELETE FROM  ACT_RU_JOB CASCADE;

 DELETE FROM   FLOWABLE.ACT_RU_VARIABLE;

 DELETE FROM  ACT_RU_TIMER_JOB;

 DELETE FROM ACT_RU_DEADLETTER_JOB;


 DELETE FROM ACT_RU_EXECUTION;


 DELETE FROM ACT_RU_JOB_FOR_DELETE;

  DELETE FROM FLOWABLE.BPM_EXECUTION;

  DELETE FROM  FLOWABLE.BPM_PROCESS;