
CREATE OR REPLACE VIEW V_ACT_RU_JOB AS
SELECT
  J.ID_,
  REV_,
  CATEGORY_,
  TYPE_,
  L.LOCK_EXP_TIME_,
  L.LOCK_OWNER_,
  EXCLUSIVE_,
  EXECUTION_ID_,
  PROCESS_INSTANCE_ID_,
  PROC_DEF_ID_,
  ELEMENT_ID_,
  ELEMENT_NAME_,
  SCOPE_ID_,
  SUB_SCOPE_ID_,
  SCOPE_TYPE_,
  SCOPE_DEFINITION_ID_,
  CORRELATION_ID_,
  RETRIES_,
  EXCEPTION_STACK_ID_,
  EXCEPTION_MSG_,
  DUEDATE_,
  REPEAT_,
  HANDLER_TYPE_,
  HANDLER_CFG_,
  CUSTOM_VALUES_ID_,
  CREATE_TIME_,
  TENANT_ID_
FROM ACT_RU_JOB J
LEFT JOIN ACT_RU_JOB_LOCK L ON J.ID_ = L.ID_
;