CREATE TABLE  ACT_RU_JOB_LOCK (
	ID_ NVARCHAR2(64) NOT NULL,
	LOCK_EXP_TIME_ TIMESTAMP (6),
	LOCK_OWNER_ NVARCHAR2(255)
)



CREATE UNIQUE INDEX ACT_RU_JOB_LOCK_UNQ  ON  ACT_RU_JOB_LOCK  (ID_);

ALTER TABLE ACT_RU_JOB_LOCK
ADD CONSTRAINT fk_act_ru_job_lock_job
FOREIGN KEY (ID_)
REFERENCES ACT_RU_JOB (ID_)
ON DELETE CASCADE;