spring:

  application:
    name: flowable-client
  liquibase:
    enabled: false
  cache:
    type: hazelcast
    cache-names: users,products,orders

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect


  datasource:
    url: jdbc:postgresql://localhost:5432/flowable2
    username: flowable
    password: flowable
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 5
      connection-timeout: 5000
      idle-timeout: 30000
      max-lifetime: 120000




  security:
    user:
      name: admin
      password: admin
      roles: ADMIN,USER

flowable:
  cmmn:
    enabled: false
  dmn:
    enabled: false
  process:
    async:
      executor:
        core-pool-size: 80
        global-acquire-lock-enabled: true







server:
  port: ${FLOWABLE_SERVER_PORT:8095}
  servlet:
    context-path: /


logging:
  level:
    org.flowable.engine: INFO

springdoc:
  swagger-ui:
    doc-expansion: none
    default-models-expand-depth: -1

app:
  flowable:
    async-executor:
      seconds-to-wait-on-shutdown: 57